import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <Link className="p-4" href={"/"}>
            Home
          </Link>
          <Link className="p-4" href={"/about"}>
            About
          </Link>
          <Link className="p-4" href={"/contact"}>
            Contact
          </Link>
          <Link className="p-4" href={"/users"}>
            Users
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
